/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	dataset "github.com/coze-dev/coze-studio/backend/api/model/data/knowledge"
	application "github.com/coze-dev/coze-studio/backend/application/knowledge"
	"github.com/coze-dev/coze-studio/backend/pkg/logs"
)

// KnowledgeRetrieve 知识库检索接口
// @router /api/knowledge/retrieve [POST]
func KnowledgeRetrieve(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dataset.KnowledgeRetrieveRequest

	// 绑定和验证请求参数
	err = c.BindAndValidate(&req)
	if err != nil {
		logs.CtxErrorf(ctx, "bind and validate request failed, err: %v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用应用服务
	resp, err := application.KnowledgeSVC.Retrieve(ctx, &req)
	if err != nil {
		logs.CtxErrorf(ctx, "knowledge retrieve failed, err: %v", err)
		internalServerErrorResponse(ctx, c, err)
		return
	}

	// 返回成功响应
	c.JSON(consts.StatusOK, resp)
}
